### ISSUE TITLE
sample/CrI3With2NNCoupling里J值的疑问

### ISSUE THREAD

**Issue by PG13s** [golddoushi/mcsolver#1]
感谢您分享的程序，有个疑问请教：最早JMCC文献里单层CrI3的J1=-2.86 meV，转换成温度是-33.14 K，但程序里默认的CrI3的J1=-16.6 K，为何这里需要除以2？

**Comment by golddoushi** [comment]
因为这个程序采用的哈密顿量（在窗口主界面上有写出）与那篇文献采用的刚好差一个1/2系数。

**Comment by wzzong** [comment]
> 因为这个程序采用的哈密顿量（在窗口主界面上有写出）与那篇文献采用的刚好差一个1/2系数。

老师，如果是按照您这篇 ”A Symmetry-Breaking Phase in Two-Dimensional FeTe2 with Ferromagnetism above Room Temperature“计算出来的J值，在输入程序时要乘以1/2吗？
