### ISSUE TITLE
在Linux下运行CrI3With2NNCoupling出现版本问题

### ISSUE THREAD

**Issue by PG13s** [golddoushi/mcsolver#3]
您好，再次打扰您了，最近我在Linux下运行CrI3With2NNCoupling时会出现unknown file or version (only support v2.2)，运行Square_XY_isotropic则可以正常运行。然后发现CrI3With2NNCoupling文件是version2.0，请问v2.2的参数文件格式相较v2.0多哪些设置。万分感谢！

**Comment by golddoushi** [comment]
可能是多了
OrbGroup: 1
Supergroup
group0 orb0-orb0
这三行。用来输出一些重整化的信息。暂时属于实验性质的feature。




      
 
     Liang Liu 
 
                                            School                                                      of                              Physics                          , State Key Laboratory for                              Crystal                          Materials,                              Shandong                                           University                            
 
              No.27, Shanda Nan Road, Jinan                   250100,                                China               


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "golddoushi/mcsolver"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午5:43
收件人:&nbsp;"golddoushi/mcsolver"<mcsolver@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[golddoushi/mcsolver] 在Linux下运行CrI3With2NNCoupling出现版本问题 (#3)





 
您好，再次打扰您了，最近我在Linux下运行CrI3With2NNCoupling时会出现unknown file or version (only support v2.2)，运行Square_XY_isotropic则可以正常运行。然后发现CrI3With2NNCoupling文件是version2.0，请问v2.2的参数文件格式相较v2.0多哪些设置。万分感谢！

**Comment by PG13s** [comment]
感谢，参数文件v2.0的基础上加了这三行对应的信息就可以识别了
